// Self-drawn unit art — "Tron" neon line-art, GENERATED BY MATH (100% in-house →
// CC0-clean for the Pages deploy, per docs/specs/assets.md §1). Each unit is a
// BARE luminous symbol drawn from a per-race mathematical shape family, so the
// race is identifiable from silhouette alone:
//   • Terran  — rectilinear circuitry: axis-aligned squares, traces, nodes.
//   • Protoss — harmonic curves: concentric circles, rings, arcs, flower-of-life.
//   • Zerg    — star polygons {n/k}: sharp continuous-stroke radial bursts.
//
// Rendering (feeds the runtime atlas, gl/atlas.ts): each emblem is drawn TWICE —
// a blurred GLOW layer (neutral light, tinted to the player's color through the
// team mask) under a thin white-hot CORE line (kept bright via the mask). On the
// dark map this reads as a team-colored neon glow with a white core. Resources
// are neutral (no mask) and use a fixed neon hue.
//
// Authored in a 64×64 viewBox, centered on (32,32), "facing" up (−y) so mobile
// units rotate toward their move target. Filter/gradient ids are local to each
// rasterized SVG document.

export type SpriteDef = {
  body: string; // inner SVG markup, full color (glow + core)
  mask?: string; // inner SVG markup, team region white / core black (omitted ⇒ never tinted)
  scale?: number; // world-size multiplier vs. the unit's interaction radius (default 1)
};

// ---- geometry primitives (return element descriptors) -----------------------
type El =
  | { d: string } // stroked path
  | { c: [number, number, number] } // stroked circle (cx,cy,r)
  | { r: [number, number, number, number] } // stroked rect (x,y,w,h)
  | { sq: [number, number, number] } // filled square (cx,cy,half)
  | { dot: [number, number, number] }; // filled circle (cx,cy,r)

const C = 32; // emblem center
const r1 = (n: number): number => Math.round(n * 10) / 10;
const P = (x: number, y: number): string => `${r1(x)},${r1(y)}`;
const gcd = (a: number, b: number): number => (b ? gcd(b, a % b) : a);

// rectilinear (Terran)
const square = (h: number, cx = C, cy = C): El => ({ r: [cx - h, cy - h, 2 * h, 2 * h] });
const rect = (w: number, h: number, cx = C, cy = C): El => ({ r: [cx - w, cy - h, 2 * w, 2 * h] });
const diamond = (h: number, cx = C, cy = C): El => ({
  d: `M${P(cx, cy - h)} L${P(cx + h, cy)} L${P(cx, cy + h)} L${P(cx - h, cy)} Z`,
});
const vbar = (x: number, y0: number, y1: number): El => ({ d: `M${P(x, y0)} L${P(x, y1)}` });
const hbar = (y: number, x0: number, x1: number): El => ({ d: `M${P(x0, y)} L${P(x1, y)}` });
const node = (cx: number, cy: number, half = 2.1): El => ({ sq: [cx, cy, half] });
const corners = (h: number, half = 2.1): El[] =>
  [
    [C - h, C - h],
    [C + h, C - h],
    [C - h, C + h],
    [C + h, C + h],
  ].map(([x, y]) => node(x!, y!, half));

// harmonic (Protoss)
const ring = (rad: number, cx = C, cy = C): El => ({ c: [cx, cy, rad] });
const dot = (cx: number, cy: number, rad: number): El => ({ dot: [cx, cy, rad] });
const triUp = (h: number, cx = C, cy = C): El => ({
  d: `M${P(cx, cy - h)} L${P(cx + h * 0.87, cy + h * 0.5)} L${P(cx - h * 0.87, cy + h * 0.5)} Z`,
});
const arc = (rad: number, a0: number, a1: number, cx = C, cy = C): El => {
  const ra0 = (a0 * Math.PI) / 180;
  const ra1 = (a1 * Math.PI) / 180;
  const large = Math.abs(a1 - a0) > 180 ? 1 : 0;
  return {
    d: `M${P(cx + rad * Math.cos(ra0), cy + rad * Math.sin(ra0))} A${r1(rad)},${r1(rad)} 0 ${large} 1 ${P(
      cx + rad * Math.cos(ra1),
      cy + rad * Math.sin(ra1),
    )}`,
  };
};
const dotsOnRing = (rad: number, n: number, rDot: number, rot = -90): El[] =>
  Array.from({ length: n }, (_, i) => {
    const a = ((rot + (i * 360) / n) * Math.PI) / 180;
    return dot(C + rad * Math.cos(a), C + rad * Math.sin(a), rDot);
  });

// star polygons {n/k} (Zerg) — handles compound stars (gcd>1 ⇒ multiple parts).
const star = (R: number, n: number, k: number, rot = -90): El[] => {
  const g = gcd(n, k);
  const out: El[] = [];
  for (let s = 0; s < g; s++) {
    const pts: string[] = [];
    let idx = s;
    for (let i = 0; i < n / g; i++) {
      const a = ((rot + (idx * 360) / n) * Math.PI) / 180;
      pts.push(P(C + R * Math.cos(a), C + R * Math.sin(a)));
      idx = (idx + k) % n;
    }
    out.push({ d: `M${pts.join(' L ')} Z` });
  }
  return out;
};

// ---- neon assembly ----------------------------------------------------------
const GLOWN = '#eaf1fb'; // neutral glow → player color via mask multiply
const CORE = '#ffffff';
const W_GLOW = 6.5;
const W_CORE = 2.0;
const BLUR = `<filter id="g" x="-80%" y="-80%" width="260%" height="260%"><feGaussianBlur stdDeviation="2.1"/></filter>`;

const draw = (els: El[], color: string, w: number): string =>
  els
    .map((e) => {
      if ('d' in e)
        return `<path d="${e.d}" fill="none" stroke="${color}" stroke-width="${w}" stroke-linejoin="round" stroke-linecap="round"/>`;
      if ('c' in e) return `<circle cx="${e.c[0]}" cy="${e.c[1]}" r="${e.c[2]}" fill="none" stroke="${color}" stroke-width="${w}"/>`;
      if ('r' in e)
        return `<rect x="${e.r[0]}" y="${e.r[1]}" width="${e.r[2]}" height="${e.r[3]}" rx="1.2" fill="none" stroke="${color}" stroke-width="${w}" stroke-linejoin="round"/>`;
      if ('sq' in e) return `<rect x="${e.sq[0] - e.sq[2]}" y="${e.sq[1] - e.sq[2]}" width="${2 * e.sq[2]}" height="${2 * e.sq[2]}" fill="${color}"/>`;
      return `<circle cx="${e.dot[0]}" cy="${e.dot[1]}" r="${e.dot[2]}" fill="${color}"/>`;
    })
    .join('');

/** Build a team-tintable neon emblem from a flat list of geometry. */
const neon = (els: El[], scale = 1.6): SpriteDef => ({
  body: `<defs>${BLUR}</defs><g filter="url(#g)">${draw(els, GLOWN, W_GLOW)}</g>${draw(els, CORE, W_CORE)}`,
  mask: `<defs>${BLUR}</defs><g filter="url(#g)">${draw(els, '#fff', W_GLOW)}</g>${draw(els, '#000', W_CORE)}`,
  scale,
});

/** Neutral (never-tinted) neon emblem in a fixed hue — for resources. */
const neonFixed = (els: El[], glow: string, core: string, scale = 1.2): SpriteDef => ({
  body: `<defs>${BLUR}</defs><g filter="url(#g)">${draw(els, glow, W_GLOW)}</g>${draw(els, core, W_CORE)}`,
  scale,
});

const U = 1.7; // default unit scale
const B = 1.0; // default building scale

// =============================================================================
//  ROSTER — full three-race lineup (docs/specs/sc1-spec.md). Each race is one
//  mathematical family; role/tier vary the parameters.
// =============================================================================
export const SPRITES: Record<string, SpriteDef> = {
  // ----------------------------- TERRAN (squares) ----------------------------
  scv: neon([square(8), dot(C, C, 2.2)], U),
  marine: neon([square(8), vbar(C, C - 14, C - 8)], U),
  firebat: neon([square(8), vbar(C - 3, C - 13, C - 8), vbar(C + 3, C - 13, C - 8)], U),
  medic: neon([square(8), vbar(C, C - 5, C + 5), hbar(C, C - 5, C + 5)], U),
  ghost: neon([diamond(9), dot(C, C, 1.8)], U),
  vulture: neon([rect(11, 6), vbar(C, C - 12, C - 6)], U),
  siegeTank: neon([rect(11, 9), vbar(C, C - 22, C - 9)], U),
  goliath: neon([square(9), vbar(C - 3, C - 18, C - 9), vbar(C + 3, C - 18, C - 9)], U),
  wraith: neon([diamond(11), diamond(5)], U),
  dropship: neon([rect(12, 8), rect(6, 4)], U),
  scienceVessel: neon([diamond(11), diamond(6), dot(C, C, 1.6)], U),
  valkyrie: neon([diamond(11), vbar(C - 4, C - 14, C - 9), vbar(C, C - 16, C - 9), vbar(C + 4, C - 14, C - 9)], U),
  battlecruiser: neon([square(20), square(12), ...corners(20, 2.4)], U),
  spiderMine: neon([square(5), dot(C, C, 1.6)], U),
  nuke: neon([rect(5, 13), triUp(5, C, C - 13)], U),
  commandCenter: neon([square(22), square(13), dot(C, C, 2.4), ...corners(22, 2.4)], B),
  supplyDepot: neon([rect(20, 11), hbar(C, C - 12, C + 12)], B),
  refinery: neon([square(18), diamond(8)], B),
  barracks: neon([square(20), rect(7, 4, C, C + 14)], B),
  engineeringBay: neon([square(19), vbar(C, C - 8, C + 8), hbar(C, C - 8, C + 8)], B),
  bunker: neon([square(16), ...corners(16, 3.2)], B),
  academy: neon([square(19), square(8), dot(C, C, 1.8)], B),
  missileTurret: neon([square(11), square(5), vbar(C, C - 18, C - 11)], B),
  factory: neon([square(20), rect(9, 6), node(C, C, 2.2)], B),
  machineShop: neon([square(11), node(C, C, 2.2)], B),
  starport: neon([square(20), diamond(9)], B),
  controlTower: neon([square(11), dot(C, C, 2)], B),
  armory: neon([square(19), vbar(C - 5, C - 10, C + 10), vbar(C + 5, C - 10, C + 10)], B),
  scienceFacility: neon([square(20), square(10), dot(C, C, 2)], B),
  physicsLab: neon([square(11), diamond(5)], B),
  covertOps: neon([square(11), dot(C, C, 1.8)], B),
  comsat: neon([square(11), ring(6)], B),
  nuclearSilo: neon([square(18), rect(5, 11)], B),

  // ----------------------------- PROTOSS (circles) ---------------------------
  probe: neon([ring(9), dot(C, C, 2.2)], U),
  zealot: neon([ring(9), arc(13, -130, -50)], U),
  dragoon: neon([ring(11), arc(15, -120, -60), dot(C, C, 1.8)], U),
  highTemplar: neon([ring(9), triUp(5)], U),
  darkTemplar: neon([ring(9), triUp(6, C, C + 1)], U),
  archon: neon([ring(12), ring(6), dot(C, C, 2.4)], U),
  darkArchon: neon([ring(12), triUp(6), dot(C, C, 1.8)], U),
  reaver: neon([ring(12), ...dotsOnRing(6, 3, 2)], U),
  observer: neon([ring(8), ring(4)], U),
  shuttle: neon([ring(11), ring(5)], U),
  scout: neon([ring(11), arc(15, -125, -90), arc(15, -90, -55)], U),
  carrier: neon([ring(22), dot(C, C, 4.5), ...dotsOnRing(12, 6, 3)], U),
  interceptor: neon([ring(5), dot(C, C, 1.6)], U),
  scarab: neon([ring(4), dot(C, C, 1.8)], U),
  arbiter: neon([ring(12), ring(6), triUp(5)], U),
  corsair: neon([ring(10), arc(13, -120, -60)], U),
  nexus: neon([ring(22), ring(13), dot(C, C, 3), ...dotsOnRing(22, 4, 2.4)], B),
  pylon: neon([diamond(13), dot(C, C, 2.4)], B), // diamond motif (canon)
  assimilator: neon([ring(17), diamond(7)], B),
  gateway: neon([ring(19), arc(13, -150, -30)], B),
  forge: neon([ring(18), triUp(8)], B),
  photonCannon: neon([ring(12), ring(5), dot(C, C, 1.8)], B),
  cyberneticsCore: neon([ring(19), ring(9), dot(C, C, 2)], B),
  shieldBattery: neon([ring(16), ring(8)], B),
  roboticsFacility: neon([ring(19), ring(8), dot(C, C, 2)], B),
  stargate: neon([ring(20), ring(10), ...dotsOnRing(20, 4, 2.2)], B),
  citadelOfAdun: neon([ring(18), triUp(9)], B),
  templarArchives: neon([ring(19), triUp(8), dot(C, C, 1.8)], B),
  roboticsSupportBay: neon([ring(13), dot(C, C, 2.2)], B),
  observatory: neon([ring(14), ring(7), dot(C, C, 1.6)], B),
  fleetBeacon: neon([ring(19), ring(9), dot(C, C, 2.2)], B),
  arbiterTribunal: neon([ring(19), ring(9), triUp(6)], B),

  // ------------------------------ ZERG (stars) -------------------------------
  larva: neon([...star(6, 3, 1), dot(C, C, 1.4)], U),
  drone: neon([...star(10, 5, 2), dot(C, C, 2)], U),
  overlord: neon([...star(13, 6, 1), ring(6)], U),
  zergling: neon(star(9, 5, 2), U),
  hydralisk: neon(star(12, 6, 2), U),
  lurker: neon([...star(13, 6, 2), dot(C, C, 2)], U),
  mutalisk: neon(star(11, 5, 2), U),
  scourge: neon(star(7, 3, 1), U),
  guardian: neon(star(14, 6, 2), U),
  devourer: neon(star(13, 7, 3), U),
  queen: neon([...star(12, 6, 2), ring(5)], U),
  defiler: neon([...star(13, 7, 2), ring(5)], U),
  ultralisk: neon(star(20, 7, 3), U),
  infestedTerran: neon([...star(9, 5, 2), dot(C, C, 1.8)], U),
  broodling: neon(star(6, 3, 1), U),
  hatchery: neon([...star(20, 6, 1), ring(8), dot(C, C, 2.4)], B),
  lair: neon([...star(20, 6, 1), ring(9), dot(C, C, 2.2)], B),
  hive: neon([...star(21, 6, 1), ring(12), ring(6)], B),
  creepColony: neon([...star(14, 5, 1), dot(C, C, 2.2)], B),
  sunkenColony: neon([...star(15, 6, 2), dot(C, C, 2.2)], B),
  sporeColony: neon([...star(14, 6, 1), ring(6)], B),
  spawningPool: neon([...star(18, 6, 1), ring(8)], B),
  evolutionChamber: neon([...star(18, 6, 1), dot(C, C, 2.4)], B),
  hydraliskDen: neon([...star(18, 6, 2), dot(C, C, 2.2)], B),
  extractor: neon([...star(16, 6, 1), diamond(6)], B),
  spire: neon([...star(16, 5, 2), dot(C, C, 2.2)], B),
  greaterSpire: neon([...star(17, 5, 2), ring(7)], B),
  queensNest: neon([...star(17, 6, 1), ring(8)], B),
  nydusCanal: neon([...star(14, 6, 1), ring(7)], B),
  ultraliskCavern: neon([...star(18, 6, 1), dot(C, C, 2.4)], B),
  defilerMound: neon([...star(18, 6, 1), ring(7), dot(C, C, 2)], B),

  // ------------------------------ RESOURCES (neutral) ------------------------
  mineral: neonFixed([diamond(10, 26, 34), diamond(13, 39, 30), diamond(7, 31, 21)], '#7ef0e6', '#dffdf8', 1.25),
  geyser: neonFixed([...star(13, 6, 1), dot(C, 24, 2), dot(35, 18, 1.5), dot(30, 13, 1.2)], '#76e89a', '#dffbe6', 1.0),
};

/** Race groupings (rollout / gallery order). */
export const ROSTER_GROUPS: { race: string; keys: string[] }[] = [
  {
    race: 'Terran',
    keys: [
      'scv', 'marine', 'firebat', 'medic', 'ghost', 'vulture', 'siegeTank', 'goliath', 'wraith', 'dropship',
      'scienceVessel', 'valkyrie', 'battlecruiser', 'spiderMine', 'nuke', 'commandCenter', 'supplyDepot', 'refinery',
      'barracks', 'engineeringBay', 'bunker', 'academy', 'missileTurret', 'factory', 'machineShop', 'starport',
      'controlTower', 'armory', 'scienceFacility', 'physicsLab', 'covertOps', 'comsat', 'nuclearSilo',
    ],
  },
  {
    race: 'Protoss',
    keys: [
      'probe', 'zealot', 'dragoon', 'highTemplar', 'darkTemplar', 'archon', 'darkArchon', 'reaver', 'observer',
      'shuttle', 'scout', 'carrier', 'interceptor', 'scarab', 'arbiter', 'corsair', 'nexus', 'pylon', 'assimilator', 'gateway',
      'forge', 'photonCannon', 'cyberneticsCore', 'shieldBattery', 'roboticsFacility', 'stargate', 'citadelOfAdun',
      'templarArchives', 'roboticsSupportBay', 'observatory', 'fleetBeacon', 'arbiterTribunal',
    ],
  },
  {
    race: 'Zerg',
    keys: [
      'larva', 'drone', 'overlord', 'zergling', 'hydralisk', 'lurker', 'mutalisk', 'scourge', 'guardian', 'devourer',
      'queen', 'defiler', 'ultralisk', 'infestedTerran', 'broodling', 'hatchery', 'lair', 'hive', 'creepColony',
      'sunkenColony', 'sporeColony', 'spawningPool', 'evolutionChamber', 'hydraliskDen', 'extractor', 'spire',
      'greaterSpire', 'queensNest', 'nydusCanal', 'ultraliskCavern', 'defilerMound',
    ],
  },
  { race: 'Neutral', keys: ['mineral', 'geyser'] },
];

/** Wrap inner markup into a standalone, sized SVG document for rasterization. */
export const svgDoc = (inner: string): string =>
  `<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64">${inner}</svg>`;
