// Self-drawn unit art — "Tron" neon line-art, GENERATED BY MATH (100% in-house →
// CC0-clean for the Pages deploy, per docs/specs/assets.md §1). Each unit is a
// BARE luminous symbol drawn from a per-race mathematical shape family, so the
// race is identifiable from silhouette alone:
//   • Terran  — rectilinear circuitry: axis-aligned squares, traces, nodes.
//   • Protoss — harmonic curves: concentric circles, rings, arcs, flower-of-life.
//   • Zerg    — star polygons {n/k}: sharp continuous-stroke radial bursts.
//
// Rendering (feeds the runtime atlas, gl/atlas.ts): each emblem is drawn TWICE —
// a blurred GLOW layer (neutral light, tinted to the player's color through the
// team mask) under a thin white-hot CORE line (kept bright via the mask). On the
// dark map this reads as a team-colored neon glow with a white core. Resources
// are neutral (no mask) and use a fixed neon hue.
//
// Authored in a 64×64 viewBox, centered on (32,32), "facing" up (−y) so mobile
// units rotate toward their move target. Filter/gradient ids are local to each
// rasterized SVG document.

export type SpriteDef = {
  body: string; // inner SVG markup, full color (glow + core)
  mask?: string; // inner SVG markup, team region white / core black (omitted ⇒ never tinted)
  scale?: number; // world-size multiplier vs. the unit's interaction radius (default 1)
};

// ---- geometry primitives (return element descriptors) -----------------------
type El =
  | { d: string } // stroked path
  | { c: [number, number, number] } // stroked circle (cx,cy,r)
  | { r: [number, number, number, number] } // stroked rect (x,y,w,h)
  | { sq: [number, number, number] } // filled square (cx,cy,half)
  | { dot: [number, number, number] }; // filled circle (cx,cy,r)

const C = 32; // emblem center
const r1 = (n: number): number => Math.round(n * 10) / 10;
const P = (x: number, y: number): string => `${r1(x)},${r1(y)}`;
const gcd = (a: number, b: number): number => (b ? gcd(b, a % b) : a);

// rectilinear (Terran)
const square = (h: number, cx = C, cy = C): El => ({ r: [cx - h, cy - h, 2 * h, 2 * h] });
const rect = (w: number, h: number, cx = C, cy = C): El => ({ r: [cx - w, cy - h, 2 * w, 2 * h] });
const diamond = (h: number, cx = C, cy = C): El => ({
  d: `M${P(cx, cy - h)} L${P(cx + h, cy)} L${P(cx, cy + h)} L${P(cx - h, cy)} Z`,
});
// rectilinear octagon (a "round" rectilinear footprint — saucers, domes, forts).
const octagon = (h: number, cx = C, cy = C): El => {
  const a = h * 0.42;
  return {
    d: `M${P(cx - a, cy - h)} L${P(cx + a, cy - h)} L${P(cx + h, cy - a)} L${P(cx + h, cy + a)} L${P(cx + a, cy + h)} L${P(cx - a, cy + h)} L${P(cx - h, cy + a)} L${P(cx - h, cy - a)} Z`,
  };
};
// lozenge: a diamond with independent width/height (slim sleek silhouettes).
const loz = (w: number, h: number, cx = C, cy = C): El => ({
  d: `M${P(cx, cy - h)} L${P(cx + w, cy)} L${P(cx, cy + h)} L${P(cx - w, cy)} Z`,
});
const vbar = (x: number, y0: number, y1: number): El => ({ d: `M${P(x, y0)} L${P(x, y1)}` });
const hbar = (y: number, x0: number, x1: number): El => ({ d: `M${P(x0, y)} L${P(x1, y)}` });
const node = (cx: number, cy: number, half = 2.1): El => ({ sq: [cx, cy, half] });
const corners = (h: number, half = 2.1): El[] =>
  [
    [C - h, C - h],
    [C + h, C - h],
    [C - h, C + h],
    [C + h, C + h],
  ].map(([x, y]) => node(x!, y!, half));

// harmonic (Protoss)
const ring = (rad: number, cx = C, cy = C): El => ({ c: [cx, cy, rad] });
const dot = (cx: number, cy: number, rad: number): El => ({ dot: [cx, cy, rad] });
const triUp = (h: number, cx = C, cy = C): El => ({
  d: `M${P(cx, cy - h)} L${P(cx + h * 0.87, cy + h * 0.5)} L${P(cx - h * 0.87, cy + h * 0.5)} Z`,
});
const arc = (rad: number, a0: number, a1: number, cx = C, cy = C): El => {
  const ra0 = (a0 * Math.PI) / 180;
  const ra1 = (a1 * Math.PI) / 180;
  const large = Math.abs(a1 - a0) > 180 ? 1 : 0;
  return {
    d: `M${P(cx + rad * Math.cos(ra0), cy + rad * Math.sin(ra0))} A${r1(rad)},${r1(rad)} 0 ${large} 1 ${P(
      cx + rad * Math.cos(ra1),
      cy + rad * Math.sin(ra1),
    )}`,
  };
};
const dotsOnRing = (rad: number, n: number, rDot: number, rot = -90): El[] =>
  Array.from({ length: n }, (_, i) => {
    const a = ((rot + (i * 360) / n) * Math.PI) / 180;
    return dot(C + rad * Math.cos(a), C + rad * Math.sin(a), rDot);
  });

// star polygons {n/k} (Zerg) — handles compound stars (gcd>1 ⇒ multiple parts).
const star = (R: number, n: number, k: number, rot = -90): El[] => {
  const g = gcd(n, k);
  const out: El[] = [];
  for (let s = 0; s < g; s++) {
    const pts: string[] = [];
    let idx = s;
    for (let i = 0; i < n / g; i++) {
      const a = ((rot + (idx * 360) / n) * Math.PI) / 180;
      pts.push(P(C + R * Math.cos(a), C + R * Math.sin(a)));
      idx = (idx + k) % n;
    }
    out.push({ d: `M${pts.join(' L ')} Z` });
  }
  return out;
};

// ---- neon assembly ----------------------------------------------------------
const GLOWN = '#eaf1fb'; // neutral glow → player color via mask multiply
const CORE = '#ffffff';
const W_GLOW = 6.5;
const W_CORE = 2.0;
const BLUR = `<filter id="g" x="-80%" y="-80%" width="260%" height="260%"><feGaussianBlur stdDeviation="2.1"/></filter>`;

const draw = (els: El[], color: string, w: number): string =>
  els
    .map((e) => {
      if ('d' in e)
        return `<path d="${e.d}" fill="none" stroke="${color}" stroke-width="${w}" stroke-linejoin="round" stroke-linecap="round"/>`;
      if ('c' in e) return `<circle cx="${e.c[0]}" cy="${e.c[1]}" r="${e.c[2]}" fill="none" stroke="${color}" stroke-width="${w}"/>`;
      if ('r' in e)
        return `<rect x="${e.r[0]}" y="${e.r[1]}" width="${e.r[2]}" height="${e.r[3]}" rx="1.2" fill="none" stroke="${color}" stroke-width="${w}" stroke-linejoin="round"/>`;
      if ('sq' in e) return `<rect x="${e.sq[0] - e.sq[2]}" y="${e.sq[1] - e.sq[2]}" width="${2 * e.sq[2]}" height="${2 * e.sq[2]}" fill="${color}"/>`;
      return `<circle cx="${e.dot[0]}" cy="${e.dot[1]}" r="${e.dot[2]}" fill="${color}"/>`;
    })
    .join('');

/** Build a team-tintable neon emblem from a flat list of geometry. */
const neon = (els: El[], scale = 1.6): SpriteDef => ({
  body: `<defs>${BLUR}</defs><g filter="url(#g)">${draw(els, GLOWN, W_GLOW)}</g>${draw(els, CORE, W_CORE)}`,
  mask: `<defs>${BLUR}</defs><g filter="url(#g)">${draw(els, '#fff', W_GLOW)}</g>${draw(els, '#000', W_CORE)}`,
  scale,
});

/** Neutral (never-tinted) neon emblem in a fixed hue — for resources. */
const neonFixed = (els: El[], glow: string, core: string, scale = 1.2): SpriteDef => ({
  body: `<defs>${BLUR}</defs><g filter="url(#g)">${draw(els, glow, W_GLOW)}</g>${draw(els, core, W_CORE)}`,
  scale,
});

const U = 1.7; // default unit scale
const B = 1.0; // default building scale

// =============================================================================
//  ROSTER — full three-race lineup (docs/specs/sc1-spec.md). Each race is one
//  mathematical family; role/tier vary the parameters.
// =============================================================================
export const SPRITES: Record<string, SpriteDef> = {
  // --------------------- TERRAN (rectilinear) — distinct silhouettes ---------
  scv: neon([square(7), node(C + 8, C - 4, 2.6)], U), // body + offset claw arm
  marine: neon([rect(4.5, 9), vbar(C, C - 16, C - 9)], U), // narrow trooper + rifle
  firebat: neon([rect(7.5, 6), node(C - 9, C, 2.8), node(C + 9, C, 2.8)], U), // wide + side tanks
  medic: neon([vbar(C, C - 11, C + 11), hbar(C, C - 11, C + 11), square(4.5)], U), // a plus (cross)
  ghost: neon([loz(5, 12), dot(C, C, 1.6)], U), // slim lozenge (stealth)
  vulture: neon([rect(3.5, 11), node(C, C + 12, 2)], U), // NARROW vertical bike + tail
  siegeTank: neon([rect(12, 8), vbar(C, C - 23, C - 8)], U), // wide hull + long cannon
  goliath: neon([square(8), vbar(C - 4, C - 18, C - 8), vbar(C + 4, C - 18, C - 8), node(C - 8, C + 9, 2.2), node(C + 8, C + 9, 2.2)], U), // walker: twin guns + legs
  wraith: neon([diamond(11)], U), // clean diamond (air)
  dropship: neon([rect(13, 8), hbar(C, C - 13, C + 13)], U), // bulky wide transport
  scienceVessel: neon([octagon(11), dot(C, C, 2)], U), // saucer
  valkyrie: neon([diamond(10), hbar(C - 2, C - 12, C + 12)], U), // air + missile rack
  battlecruiser: neon([square(20), square(12), ...corners(20, 2.4)], U), // capital
  spiderMine: neon([square(4), node(C - 6, C - 6, 1.8), node(C + 6, C - 6, 1.8), node(C - 6, C + 6, 1.8), node(C + 6, C + 6, 1.8)], U), // tiny + 4 legs
  nuke: neon([rect(3.5, 12), triUp(4, C, C - 12)], U), // missile
  commandCenter: neon([square(21), square(12), dot(C, C, 2.4), ...corners(21, 2.4)], B),
  supplyDepot: neon([rect(20, 9), hbar(C - 4, C - 17, C + 17), hbar(C + 4, C - 17, C + 17)], B), // low + slats
  refinery: neon([square(15), diamond(7), node(C - 16, C, 2.4), node(C + 16, C, 2.4)], B), // tanks
  barracks: neon([square(19), rect(6, 4, C, C + 15)], B), // bay door
  engineeringBay: neon([square(18), vbar(C, C - 10, C + 10), hbar(C, C - 10, C + 10)], B), // inner cross
  bunker: neon([octagon(15), ...corners(11, 3.2)], B), // fort: octagon + heavy nodes
  academy: neon([square(18), rect(9, 5, C, C - 1)], B), // inner screen
  missileTurret: neon([square(8, C, C + 7), square(6, C, C - 6), vbar(C, C - 18, C - 12)], B), // stacked turret
  factory: neon([rect(20, 14), rect(8, 5), node(C + 14, C - 9, 2.4)], B), // wide industrial
  machineShop: neon([square(10), node(C - 5, C - 5, 1.9), node(C + 5, C - 5, 1.9), node(C - 5, C + 5, 1.9), node(C + 5, C + 5, 1.9)], B), // gear cluster
  starport: neon([square(19), diamond(9)], B), // air bay
  controlTower: neon([square(8), vbar(C, C - 19, C - 8)], B), // antenna tower
  armory: neon([square(18), vbar(C - 5, C - 11, C + 11), vbar(C + 5, C - 11, C + 11)], B), // twin racks
  scienceFacility: neon([square(19), octagon(9), dot(C, C, 1.8)], B), // dome lab
  physicsLab: neon([square(10), diamond(5)], B),
  covertOps: neon([square(10), hbar(C, C - 5, C + 5)], B), // slit (vs tower/lab)
  comsat: neon([square(9), arc(7, -160, -20, C, C - 1)], B), // dish arc
  nuclearSilo: neon([square(17), rect(4, 9), hbar(C, C - 17, C + 17)], B), // silo + hatch

  // --------------------- PROTOSS (harmonic) — distinct silhouettes -----------
  probe: neon([ring(8), dot(C, C, 2.2)], U),
  zealot: neon([ring(9), arc(13, -135, -100), arc(13, -80, -45)], U), // twin blade arcs
  dragoon: neon([ring(11), dot(C, C, 2.4), arc(15, -125, -55)], U), // body + leg arc
  highTemplar: neon([ring(8), triUp(5)], U), // psi triangle
  darkTemplar: neon([ring(8), arc(11, -150, -30), dot(C, C, 1.6)], U), // crescent + core
  archon: neon([ring(12), ring(6), dot(C, C, 3.2)], U), // energy ball
  darkArchon: neon([ring(12), arc(8, -160, -20), triUp(4)], U),
  reaver: neon([ring(11), ...dotsOnRing(5, 3, 2.2)], U), // scarab cluster
  observer: neon([ring(7), ring(3.5)], U), // tiny eye
  shuttle: neon([ring(11), dot(C - 5, C, 2.2), dot(C + 5, C, 2.2)], U), // twin cargo pods
  scout: neon([ring(10), arc(14, -130, -90), arc(14, -90, -50), dot(C, C, 1.6)], U), // swept wings
  carrier: neon([ring(22), dot(C, C, 4.5), ...dotsOnRing(13, 6, 2.6)], U), // flower-of-life
  interceptor: neon([ring(6), dot(C, C, 1.4)], U),
  scarab: neon([triUp(5), dot(C, C, 1.4)], U), // tiny wedge (vs interceptor ring)
  arbiter: neon([ring(12), ring(6), triUp(5)], U),
  corsair: neon([ring(10), arc(13, -110, -70)], U), // single forward arc
  nexus: neon([ring(22), ring(13), dot(C, C, 3), ...dotsOnRing(22, 4, 2.4)], B),
  pylon: neon([diamond(13), dot(C, C, 2.4)], B), // diamond motif (canon)
  assimilator: neon([ring(16), diamond(7)], B), // gas
  gateway: neon([arc(18, -160, -20), arc(18, 20, 160), dot(C, C, 2.4)], B), // split portal
  forge: neon([ring(17), triUp(8)], B),
  photonCannon: neon([ring(10), dot(C, C, 2.4), ...dotsOnRing(13, 3, 2)], B), // 3 prongs
  cyberneticsCore: neon([ring(18), ring(9), ...dotsOnRing(13, 3, 2)], B),
  shieldBattery: neon([ring(16), arc(9, -150, -30)], B), // crescent cell
  roboticsFacility: neon([ring(18), square(8)], B), // square-in-circle (robotic)
  stargate: neon([ring(19), ...dotsOnRing(19, 6, 2.2), dot(C, C, 2)], B), // 6-node portal
  citadelOfAdun: neon([ring(17), triUp(9), dot(C, C, 1.6)], B),
  templarArchives: neon([ring(18), triUp(7), ...dotsOnRing(11, 2, 1.8)], B),
  roboticsSupportBay: neon([ring(12), square(6)], B), // small robotic
  observatory: neon([ring(13), ring(6.5), dot(C, C, 1.6)], B), // eye
  fleetBeacon: neon([ring(18), arc(9, -150, -30), dot(C, C, 2)], B), // crescent beacon
  arbiterTribunal: neon([ring(18), ring(9), triUp(6)], B),

  // ----------------------- ZERG (stars) — distinct silhouettes ---------------
  larva: neon([...star(6, 3, 1), dot(C, C, 1.4)], U), // tiny triangle + core
  drone: neon([...star(10, 5, 2), dot(C, C, 2)], U), // pentagram + core
  overlord: neon([...star(13, 6, 1), ring(6), dot(C, C, 1.6)], U), // hexagon + eye
  zergling: neon(star(9, 5, 2), U), // small pentagram
  hydralisk: neon(star(12, 6, 2), U), // hexagram
  lurker: neon([...star(12, 6, 3), dot(C, C, 2)], U), // {6/3} burst + core
  mutalisk: neon([...star(11, 5, 2), dot(C, C, 1.4)], U),
  scourge: neon(star(8, 4, 1), U), // small 4-point (diamond)
  guardian: neon(star(15, 6, 2), U), // big hexagram
  devourer: neon(star(13, 8, 3), U), // octagram {8/3}
  queen: neon([...star(12, 6, 2), ring(5)], U),
  defiler: neon([...star(13, 7, 2), ring(5)], U), // heptagram + ring
  ultralisk: neon(star(20, 7, 3), U), // {7/3} (hero)
  infestedTerran: neon([...star(9, 5, 2), dot(C, C, 1.8)], U),
  broodling: neon(star(6, 3, 1), U), // tiny triangle
  hatchery: neon([...star(20, 6, 1), dot(C, C, 2.4)], B), // hexagon mound
  lair: neon([...star(20, 6, 1), ring(8), dot(C, C, 2)], B), // + eye (tier 2)
  hive: neon([...star(21, 6, 1), ring(11), ring(5)], B), // double ring (tier 3)
  creepColony: neon([...star(14, 5, 1), dot(C, C, 2.2)], B), // pentagon
  sunkenColony: neon([...star(15, 6, 2), dot(C, C, 2.2)], B), // hexagram (AG)
  sporeColony: neon([...star(14, 6, 2), ring(6)], B), // hexagram + eye (AA)
  spawningPool: neon([...star(18, 6, 1), ...star(8, 6, 1)], B), // nested hexagons
  evolutionChamber: neon([...star(18, 5, 1), ring(7)], B), // pentagon + ring
  hydraliskDen: neon([...star(18, 6, 2), dot(C, C, 2.2)], B), // hexagram den
  extractor: neon([...star(16, 6, 1), diamond(6)], B), // hexagon + gas
  spire: neon([...star(16, 5, 2), dot(C, C, 2.2)], B), // pentagram spire
  greaterSpire: neon([...star(17, 7, 3), ring(6)], B), // heptagram (taller)
  queensNest: neon([...star(17, 5, 1), ring(7)], B), // pentagon + ring
  nydusCanal: neon([...star(14, 6, 1), ring(8)], B), // big tunnel mouth
  ultraliskCavern: neon([...star(18, 7, 1), dot(C, C, 2.4)], B), // heptagon
  defilerMound: neon([...star(18, 7, 2), ring(6)], B), // {7/2} + ring

  // ------------------------------ RESOURCES (neutral) ------------------------
  mineral: neonFixed([diamond(10, 26, 34), diamond(13, 39, 30), diamond(7, 31, 21)], '#7ef0e6', '#dffdf8', 1.25),
  geyser: neonFixed([...star(13, 6, 1), dot(C, 24, 2), dot(35, 18, 1.5), dot(30, 13, 1.2)], '#76e89a', '#dffbe6', 1.0),
};

/** Race groupings (rollout / gallery order). */
export const ROSTER_GROUPS: { race: string; keys: string[] }[] = [
  {
    race: 'Terran',
    keys: [
      'scv', 'marine', 'firebat', 'medic', 'ghost', 'vulture', 'siegeTank', 'goliath', 'wraith', 'dropship',
      'scienceVessel', 'valkyrie', 'battlecruiser', 'spiderMine', 'nuke', 'commandCenter', 'supplyDepot', 'refinery',
      'barracks', 'engineeringBay', 'bunker', 'academy', 'missileTurret', 'factory', 'machineShop', 'starport',
      'controlTower', 'armory', 'scienceFacility', 'physicsLab', 'covertOps', 'comsat', 'nuclearSilo',
    ],
  },
  {
    race: 'Protoss',
    keys: [
      'probe', 'zealot', 'dragoon', 'highTemplar', 'darkTemplar', 'archon', 'darkArchon', 'reaver', 'observer',
      'shuttle', 'scout', 'carrier', 'interceptor', 'scarab', 'arbiter', 'corsair', 'nexus', 'pylon', 'assimilator', 'gateway',
      'forge', 'photonCannon', 'cyberneticsCore', 'shieldBattery', 'roboticsFacility', 'stargate', 'citadelOfAdun',
      'templarArchives', 'roboticsSupportBay', 'observatory', 'fleetBeacon', 'arbiterTribunal',
    ],
  },
  {
    race: 'Zerg',
    keys: [
      'larva', 'drone', 'overlord', 'zergling', 'hydralisk', 'lurker', 'mutalisk', 'scourge', 'guardian', 'devourer',
      'queen', 'defiler', 'ultralisk', 'infestedTerran', 'broodling', 'hatchery', 'lair', 'hive', 'creepColony',
      'sunkenColony', 'sporeColony', 'spawningPool', 'evolutionChamber', 'hydraliskDen', 'extractor', 'spire',
      'greaterSpire', 'queensNest', 'nydusCanal', 'ultraliskCavern', 'defilerMound',
    ],
  },
  { race: 'Neutral', keys: ['mineral', 'geyser'] },
];

/** Wrap inner markup into a standalone, sized SVG document for rasterization. */
export const svgDoc = (inner: string): string =>
  `<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64">${inner}</svg>`;
