// Self-drawn unit art — "Tron" neon line-art, GENERATED BY MATH (100% in-house →
// CC0-clean for the Pages deploy, per docs/specs/assets.md §1). Each unit is a
// BARE luminous symbol drawn from a per-race mathematical shape family, so the
// race is identifiable from silhouette alone:
//   • Terran  — rectilinear circuitry: axis-aligned squares, traces, nodes.
//   • Protoss — harmonic curves: concentric circles, rings, arcs, flower-of-life.
//   • Zerg    — star polygons {n/k}: sharp continuous-stroke radial bursts.
//
// Rendering (feeds the runtime atlas, gl/atlas.ts): each emblem is drawn TWICE —
// a blurred GLOW layer (neutral light, tinted to the player's color through the
// team mask) under a thin white-hot CORE line (kept bright via the mask). On the
// dark map this reads as a team-colored neon glow with a white core. Resources
// are neutral (no mask) and use a fixed neon hue.
//
// Authored in a 64×64 viewBox, centered on (32,32), "facing" up (−y) so mobile
// units rotate toward their move target. Filter/gradient ids are local to each
// rasterized SVG document.

export type SpriteDef = {
  body: string; // inner SVG markup, full color (glow + core)
  mask?: string; // inner SVG markup, team region white / core black (omitted ⇒ never tinted)
  scale?: number; // world-size multiplier vs. the unit's interaction radius (default 1)
};

// ---- geometry primitives (return element descriptors) -----------------------
type El =
  | { d: string } // stroked path
  | { c: [number, number, number] } // stroked circle (cx,cy,r)
  | { r: [number, number, number, number] } // stroked rect (x,y,w,h)
  | { sq: [number, number, number] } // filled square (cx,cy,half)
  | { dot: [number, number, number] }; // filled circle (cx,cy,r)

const C = 32; // emblem center
const TAU = Math.PI * 2;
const r1 = (n: number): number => Math.round(n * 10) / 10;
const P = (x: number, y: number): string => `${r1(x)},${r1(y)}`;

// rectilinear (Terran)
const square = (h: number, cx = C, cy = C): El => ({ r: [cx - h, cy - h, 2 * h, 2 * h] });
const rect = (w: number, h: number, cx = C, cy = C): El => ({ r: [cx - w, cy - h, 2 * w, 2 * h] });
const diamond = (h: number, cx = C, cy = C): El => ({
  d: `M${P(cx, cy - h)} L${P(cx + h, cy)} L${P(cx, cy + h)} L${P(cx - h, cy)} Z`,
});
// rectilinear octagon (a "round" rectilinear footprint — saucers, domes, forts).
const octagon = (h: number, cx = C, cy = C): El => {
  const a = h * 0.42;
  return {
    d: `M${P(cx - a, cy - h)} L${P(cx + a, cy - h)} L${P(cx + h, cy - a)} L${P(cx + h, cy + a)} L${P(cx + a, cy + h)} L${P(cx - a, cy + h)} L${P(cx - h, cy + a)} L${P(cx - h, cy - a)} Z`,
  };
};
// lozenge: a diamond with independent width/height (slim sleek silhouettes).
const loz = (w: number, h: number, cx = C, cy = C): El => ({
  d: `M${P(cx, cy - h)} L${P(cx + w, cy)} L${P(cx, cy + h)} L${P(cx - w, cy)} Z`,
});
const vbar = (x: number, y0: number, y1: number): El => ({ d: `M${P(x, y0)} L${P(x, y1)}` });
const hbar = (y: number, x0: number, x1: number): El => ({ d: `M${P(x0, y)} L${P(x1, y)}` });
const node = (cx: number, cy: number, half = 2.1): El => ({ sq: [cx, cy, half] });
const corners = (h: number, half = 2.1): El[] =>
  [
    [C - h, C - h],
    [C + h, C - h],
    [C - h, C + h],
    [C + h, C + h],
  ].map(([x, y]) => node(x!, y!, half));

// harmonic (Protoss)
const ring = (rad: number, cx = C, cy = C): El => ({ c: [cx, cy, rad] });
const dot = (cx: number, cy: number, rad: number): El => ({ dot: [cx, cy, rad] });
const triUp = (h: number, cx = C, cy = C): El => ({
  d: `M${P(cx, cy - h)} L${P(cx + h * 0.87, cy + h * 0.5)} L${P(cx - h * 0.87, cy + h * 0.5)} Z`,
});
const arc = (rad: number, a0: number, a1: number, cx = C, cy = C): El => {
  const ra0 = (a0 * Math.PI) / 180;
  const ra1 = (a1 * Math.PI) / 180;
  const large = Math.abs(a1 - a0) > 180 ? 1 : 0;
  return {
    d: `M${P(cx + rad * Math.cos(ra0), cy + rad * Math.sin(ra0))} A${r1(rad)},${r1(rad)} 0 ${large} 1 ${P(
      cx + rad * Math.cos(ra1),
      cy + rad * Math.sin(ra1),
    )}`,
  };
};
const dotsOnRing = (rad: number, n: number, rDot: number, rot = -90): El[] =>
  Array.from({ length: n }, (_, i) => {
    const a = ((rot + (i * 360) / n) * Math.PI) / 180;
    return dot(C + rad * Math.cos(a), C + rad * Math.sin(a), rDot);
  });

// Superformula (Gielis) outline (Zerg) — organic + sharp. Sampled densely into a
// closed path: the glow softens the segments into smooth chitin curves between
// SHARP cusps (not a hard star polygon). `nn` low ⇒ spiky claws, high ⇒ ridged
// mound; `asym` makes it lopsided (organic); `sy` elongates (spires).
const sfPath = (R: number, m: number, nn: number, asym = 0.14, sy = 1, rot = -90, steps = 150): El => {
  const raw: number[] = [];
  for (let i = 0; i < steps; i++) {
    const t = (m * ((i / steps) * TAU)) / 4;
    raw.push(Math.pow(Math.pow(Math.abs(Math.cos(t)), nn) + Math.pow(Math.abs(Math.sin(t)), nn), -1 / nn));
  }
  const max = Math.max(...raw) || 1;
  const pts: string[] = [];
  for (let i = 0; i < steps; i++) {
    const th = (i / steps) * TAU;
    // two modulations — one slow lopsided bias, one non-integer harmonic — break
    // the radial symmetry so the shape reads as a lumpy organism, not a star.
    const organic = (1 + asym * Math.sin(th + 0.6)) * (1 + 0.5 * asym * Math.sin(2.3 * th + 1.1));
    const rr = (R / max) * raw[i]! * organic;
    const ang = th + (rot * Math.PI) / 180;
    pts.push(P(C + rr * Math.cos(ang), C + rr * Math.sin(ang) * sy));
  }
  return { d: `M${pts.join(' L ')} Z` };
};
// rounded, lumpy, asymmetric organic body (nn high ⇒ no hard spikes; the
// irregular modulation in sfPath supplies the "alive" lopsided lumps).
const blob = (R: number, m: number, lump = 0.25, sy = 1): El => sfPath(R, m, 2, lump, sy);
// sharp barbs (spines/claws) radiating outward, with organic angular jitter so
// they read as a living bristle, not a regular star.
const spikes = (n: number, r0: number, r1: number, rot = -90, w = 0.3, jitter = 0.16): El[] =>
  Array.from({ length: n }, (_, i) => {
    const a = (rot * Math.PI) / 180 + (i * TAU) / n + Math.sin(i * 2.7) * jitter;
    return {
      d: `M${P(C + r0 * Math.cos(a - w), C + r0 * Math.sin(a - w))} L${P(C + r1 * Math.cos(a), C + r1 * Math.sin(a))} L${P(C + r0 * Math.cos(a + w), C + r0 * Math.sin(a + w))}`,
    };
  });
// paired curved talons sweeping up-forward (melee Zerg).
const talons = (spread: number, reach: number, curl: number): El[] => [
  { d: `M${P(C - spread, C + 4)} Q${P(C - spread - curl, C - reach * 0.5)} ${P(C - spread * 0.3, C - reach)}` },
  { d: `M${P(C + spread, C + 4)} Q${P(C + spread + curl, C - reach * 0.5)} ${P(C + spread * 0.3, C - reach)}` },
];

// ---- neon assembly ----------------------------------------------------------
const GLOWN = '#eaf1fb'; // neutral glow → player color via mask multiply
const CORE = '#ffffff';
const W_GLOW = 6.5;
const W_CORE = 2.0;
const BLUR = `<filter id="g" x="-80%" y="-80%" width="260%" height="260%"><feGaussianBlur stdDeviation="2.1"/></filter>`;

const draw = (els: El[], color: string, w: number): string =>
  els
    .map((e) => {
      if ('d' in e)
        return `<path d="${e.d}" fill="none" stroke="${color}" stroke-width="${w}" stroke-linejoin="round" stroke-linecap="round"/>`;
      if ('c' in e) return `<circle cx="${e.c[0]}" cy="${e.c[1]}" r="${e.c[2]}" fill="none" stroke="${color}" stroke-width="${w}"/>`;
      if ('r' in e)
        return `<rect x="${e.r[0]}" y="${e.r[1]}" width="${e.r[2]}" height="${e.r[3]}" rx="1.2" fill="none" stroke="${color}" stroke-width="${w}" stroke-linejoin="round"/>`;
      if ('sq' in e) return `<rect x="${e.sq[0] - e.sq[2]}" y="${e.sq[1] - e.sq[2]}" width="${2 * e.sq[2]}" height="${2 * e.sq[2]}" fill="${color}"/>`;
      return `<circle cx="${e.dot[0]}" cy="${e.dot[1]}" r="${e.dot[2]}" fill="${color}"/>`;
    })
    .join('');

/** Build a team-tintable neon emblem from a flat list of geometry. */
const neon = (els: El[], scale = 1.6): SpriteDef => ({
  body: `<defs>${BLUR}</defs><g filter="url(#g)">${draw(els, GLOWN, W_GLOW)}</g>${draw(els, CORE, W_CORE)}`,
  mask: `<defs>${BLUR}</defs><g filter="url(#g)">${draw(els, '#fff', W_GLOW)}</g>${draw(els, '#000', W_CORE)}`,
  scale,
});

/** Neutral (never-tinted) neon emblem in a fixed hue — for resources. */
const neonFixed = (els: El[], glow: string, core: string, scale = 1.2): SpriteDef => ({
  body: `<defs>${BLUR}</defs><g filter="url(#g)">${draw(els, glow, W_GLOW)}</g>${draw(els, core, W_CORE)}`,
  scale,
});

const U = 1.7; // default unit scale
const B = 1.0; // default building scale

// =============================================================================
//  ROSTER — full three-race lineup (docs/specs/sc1-spec.md). Each race is one
//  mathematical family; role/tier vary the parameters.
// =============================================================================
export const SPRITES: Record<string, SpriteDef> = {
  // --------------------- TERRAN (rectilinear) — distinct silhouettes ---------
  scv: neon([square(7), node(C + 8, C - 4, 2.6)], U), // body + offset claw arm
  marine: neon([rect(4.5, 9), vbar(C, C - 16, C - 9)], U), // narrow trooper + rifle
  firebat: neon([rect(7.5, 6), node(C - 9, C, 2.8), node(C + 9, C, 2.8)], U), // wide + side tanks
  medic: neon([vbar(C, C - 11, C + 11), hbar(C, C - 11, C + 11), square(4.5)], U), // a plus (cross)
  ghost: neon([loz(5, 12), dot(C, C, 1.6)], U), // slim lozenge (stealth)
  vulture: neon([rect(3.5, 11), node(C, C + 12, 2)], U), // NARROW vertical bike + tail
  siegeTank: neon([rect(12, 8), vbar(C, C - 23, C - 8)], U), // wide hull + long cannon
  goliath: neon([square(8), vbar(C - 4, C - 18, C - 8), vbar(C + 4, C - 18, C - 8), node(C - 8, C + 9, 2.2), node(C + 8, C + 9, 2.2)], U), // walker: twin guns + legs
  wraith: neon([diamond(11)], U), // clean diamond (air)
  dropship: neon([rect(13, 8), hbar(C, C - 13, C + 13)], U), // bulky wide transport
  scienceVessel: neon([octagon(11), dot(C, C, 2)], U), // saucer
  valkyrie: neon([diamond(10), hbar(C - 2, C - 12, C + 12)], U), // air + missile rack
  battlecruiser: neon([square(20), square(12), ...corners(20, 2.4)], U), // capital
  spiderMine: neon([square(4), node(C - 6, C - 6, 1.8), node(C + 6, C - 6, 1.8), node(C - 6, C + 6, 1.8), node(C + 6, C + 6, 1.8)], U), // tiny + 4 legs
  nuke: neon([rect(3.5, 12), triUp(4, C, C - 12)], U), // missile
  commandCenter: neon([square(21), square(12), dot(C, C, 2.4), ...corners(21, 2.4)], B),
  supplyDepot: neon([rect(20, 9), hbar(C - 4, C - 17, C + 17), hbar(C + 4, C - 17, C + 17)], B), // low + slats
  refinery: neon([square(15), diamond(7), node(C - 16, C, 2.4), node(C + 16, C, 2.4)], B), // tanks
  barracks: neon([square(19), rect(6, 4, C, C + 15)], B), // bay door
  engineeringBay: neon([square(18), vbar(C, C - 10, C + 10), hbar(C, C - 10, C + 10)], B), // inner cross
  bunker: neon([octagon(15), ...corners(11, 3.2)], B), // fort: octagon + heavy nodes
  academy: neon([square(18), rect(9, 5, C, C - 1)], B), // inner screen
  missileTurret: neon([square(8, C, C + 7), square(6, C, C - 6), vbar(C, C - 18, C - 12)], B), // stacked turret
  factory: neon([rect(20, 14), rect(8, 5), node(C + 14, C - 9, 2.4)], B), // wide industrial
  machineShop: neon([square(10), node(C - 5, C - 5, 1.9), node(C + 5, C - 5, 1.9), node(C - 5, C + 5, 1.9), node(C + 5, C + 5, 1.9)], B), // gear cluster
  starport: neon([square(19), diamond(9)], B), // air bay
  controlTower: neon([square(8), vbar(C, C - 19, C - 8)], B), // antenna tower
  armory: neon([square(18), vbar(C - 5, C - 11, C + 11), vbar(C + 5, C - 11, C + 11)], B), // twin racks
  scienceFacility: neon([square(19), octagon(9), dot(C, C, 1.8)], B), // dome lab
  physicsLab: neon([square(10), diamond(5)], B),
  covertOps: neon([square(10), hbar(C, C - 5, C + 5)], B), // slit (vs tower/lab)
  comsat: neon([square(9), arc(7, -160, -20, C, C - 1)], B), // dish arc
  nuclearSilo: neon([square(17), rect(4, 9), hbar(C, C - 17, C + 17)], B), // silo + hatch

  // --------------------- PROTOSS (harmonic) — distinct silhouettes -----------
  probe: neon([ring(8), dot(C, C, 2.2)], U),
  zealot: neon([ring(9), arc(13, -135, -100), arc(13, -80, -45)], U), // twin blade arcs
  dragoon: neon([ring(11), dot(C, C, 2.4), arc(15, -125, -55)], U), // body + leg arc
  highTemplar: neon([ring(8), triUp(5)], U), // psi triangle
  darkTemplar: neon([ring(8), arc(11, -150, -30), dot(C, C, 1.6)], U), // crescent + core
  archon: neon([ring(12), ring(6), dot(C, C, 3.2)], U), // energy ball
  darkArchon: neon([ring(12), arc(8, -160, -20), triUp(4)], U),
  reaver: neon([ring(11), ...dotsOnRing(5, 3, 2.2)], U), // scarab cluster
  observer: neon([ring(7), ring(3.5)], U), // tiny eye
  shuttle: neon([ring(11), dot(C - 5, C, 2.2), dot(C + 5, C, 2.2)], U), // twin cargo pods
  scout: neon([ring(10), arc(14, -130, -90), arc(14, -90, -50), dot(C, C, 1.6)], U), // swept wings
  carrier: neon([ring(22), dot(C, C, 4.5), ...dotsOnRing(13, 6, 2.6)], U), // flower-of-life
  interceptor: neon([ring(6), dot(C, C, 1.4)], U),
  scarab: neon([triUp(5), dot(C, C, 1.4)], U), // tiny wedge (vs interceptor ring)
  arbiter: neon([ring(12), ring(6), triUp(5)], U),
  corsair: neon([ring(10), arc(13, -110, -70)], U), // single forward arc
  nexus: neon([ring(22), ring(13), dot(C, C, 3), ...dotsOnRing(22, 4, 2.4)], B),
  pylon: neon([diamond(13), dot(C, C, 2.4)], B), // diamond motif (canon)
  assimilator: neon([ring(16), diamond(7)], B), // gas
  gateway: neon([arc(18, -160, -20), arc(18, 20, 160), dot(C, C, 2.4)], B), // split portal
  forge: neon([ring(17), triUp(8)], B),
  photonCannon: neon([ring(10), dot(C, C, 2.4), ...dotsOnRing(13, 3, 2)], B), // 3 prongs
  cyberneticsCore: neon([ring(18), ring(9), ...dotsOnRing(13, 3, 2)], B),
  shieldBattery: neon([ring(16), arc(9, -150, -30)], B), // crescent cell
  roboticsFacility: neon([ring(18), square(8)], B), // square-in-circle (robotic)
  stargate: neon([ring(19), ...dotsOnRing(19, 6, 2.2), dot(C, C, 2)], B), // 6-node portal
  citadelOfAdun: neon([ring(17), triUp(9), dot(C, C, 1.6)], B),
  templarArchives: neon([ring(18), triUp(7), ...dotsOnRing(11, 2, 1.8)], B),
  roboticsSupportBay: neon([ring(12), square(6)], B), // small robotic
  observatory: neon([ring(13), ring(6.5), dot(C, C, 1.6)], B), // eye
  fleetBeacon: neon([ring(18), arc(9, -150, -30), dot(C, C, 2)], B), // crescent beacon
  arbiterTribunal: neon([ring(18), ring(9), triUp(6)], B),

  // ----- ZERG (organic-sharp superformula carapace + asymmetry + talons) -----
  larva: neon([blob(7, 3, 0.4, 1.45), dot(C, C, 1.4)], U), // soft grub (no spikes)
  drone: neon([blob(8, 4, 0.3), ...spikes(5, 7, 12), dot(C, C, 2)], U),
  overlord: neon([blob(13, 5, 0.22), ring(6), dot(C, C, 1.5)], U), // soft sac + eye
  zergling: neon([blob(7, 3, 0.32), ...talons(4, 9, 5), ...spikes(3, 6, 11, 90)], U), // claws + back spikes
  hydralisk: neon([blob(8, 4, 0.3), ...spikes(7, 7, 15)], U), // needle spines
  lurker: neon([blob(8, 5, 0.25), ...spikes(9, 7, 16)], U), // urchin
  mutalisk: neon([blob(9, 4, 0.42), ...spikes(3, 8, 14)], U), // asymmetric flyer
  scourge: neon([blob(5, 3, 0.35), ...spikes(3, 5, 10)], U), // dart
  guardian: neon([blob(11, 4, 0.28, 1.1), ...spikes(5, 10, 15)], U),
  devourer: neon([blob(10, 5, 0.28), ...spikes(7, 9, 15)], U),
  queen: neon([blob(9, 4, 0.3), ring(5), ...spikes(4, 8, 13)], U), // caster sac
  defiler: neon([blob(9, 5, 0.28), ring(5), ...spikes(6, 8, 14)], U),
  ultralisk: neon([blob(11, 4, 0.24), ...talons(6, 15, 7), ...spikes(4, 10, 15, 90)], U), // tusks + back (hero)
  infestedTerran: neon([blob(7, 4, 0.32), ...spikes(4, 6, 11), dot(C, C, 1.8)], U),
  broodling: neon([blob(5, 3, 0.34), ...spikes(3, 5, 9)], U),
  hatchery: neon([blob(15, 5, 0.2), ...spikes(5, 15, 19), ring(7), dot(C, C, 2.2)], B), // mound
  lair: neon([blob(15, 5, 0.2), ...spikes(6, 15, 19), ring(9), dot(C, C, 2)], B), // tier 2
  hive: neon([blob(16, 6, 0.2), ...spikes(7, 16, 20), ring(11), ring(5)], B), // tier 3
  creepColony: neon([blob(11, 5, 0.22), ...spikes(5, 11, 15), dot(C, C, 2.2)], B),
  sunkenColony: neon([blob(9, 4, 0.2), ...spikes(4, 9, 21), dot(C, C, 2.2)], B), // long tentacles (AG)
  sporeColony: neon([blob(10, 6, 0.2), ...spikes(6, 10, 17), ring(6)], B), // + eye (AA)
  spawningPool: neon([blob(14, 5, 0.2), blob(7, 5, 0.2)], B), // nested
  evolutionChamber: neon([blob(14, 6, 0.2), ...spikes(6, 14, 17), ring(7)], B),
  hydraliskDen: neon([blob(14, 5, 0.22), ...spikes(6, 13, 19), dot(C, C, 2.2)], B), // spiny den
  extractor: neon([blob(13, 5, 0.2), ...spikes(5, 13, 16), diamond(6)], B), // gas
  spire: neon([blob(7, 3, 0.22, 1.6), ...spikes(3, 8, 24, -90, 0.2), dot(C, C, 2)], B), // tall spire
  greaterSpire: neon([blob(8, 4, 0.22, 1.55), ...spikes(4, 9, 24, -90, 0.2), ring(5)], B),
  queensNest: neon([blob(13, 5, 0.2), ...spikes(5, 13, 16), ring(7)], B),
  nydusCanal: neon([blob(12, 6, 0.2), ring(8)], B), // tunnel mouth (blunt)
  ultraliskCavern: neon([blob(14, 5, 0.2), ...spikes(5, 13, 17), dot(C, C, 2.4)], B),
  defilerMound: neon([blob(14, 6, 0.2), ...spikes(6, 13, 16), ring(6)], B),

  // ------------------------------ RESOURCES (neutral) ------------------------
  mineral: neonFixed([diamond(10, 26, 34), diamond(13, 39, 30), diamond(7, 31, 21)], '#7ef0e6', '#dffdf8', 1.25),
  geyser: neonFixed([blob(12, 6, 0.18), dot(C, 24, 2), dot(35, 18, 1.5), dot(30, 13, 1.2)], '#76e89a', '#dffbe6', 1.0),
};

/** Race groupings (rollout / gallery order). */
export const ROSTER_GROUPS: { race: string; keys: string[] }[] = [
  {
    race: 'Terran',
    keys: [
      'scv', 'marine', 'firebat', 'medic', 'ghost', 'vulture', 'siegeTank', 'goliath', 'wraith', 'dropship',
      'scienceVessel', 'valkyrie', 'battlecruiser', 'spiderMine', 'nuke', 'commandCenter', 'supplyDepot', 'refinery',
      'barracks', 'engineeringBay', 'bunker', 'academy', 'missileTurret', 'factory', 'machineShop', 'starport',
      'controlTower', 'armory', 'scienceFacility', 'physicsLab', 'covertOps', 'comsat', 'nuclearSilo',
    ],
  },
  {
    race: 'Protoss',
    keys: [
      'probe', 'zealot', 'dragoon', 'highTemplar', 'darkTemplar', 'archon', 'darkArchon', 'reaver', 'observer',
      'shuttle', 'scout', 'carrier', 'interceptor', 'scarab', 'arbiter', 'corsair', 'nexus', 'pylon', 'assimilator', 'gateway',
      'forge', 'photonCannon', 'cyberneticsCore', 'shieldBattery', 'roboticsFacility', 'stargate', 'citadelOfAdun',
      'templarArchives', 'roboticsSupportBay', 'observatory', 'fleetBeacon', 'arbiterTribunal',
    ],
  },
  {
    race: 'Zerg',
    keys: [
      'larva', 'drone', 'overlord', 'zergling', 'hydralisk', 'lurker', 'mutalisk', 'scourge', 'guardian', 'devourer',
      'queen', 'defiler', 'ultralisk', 'infestedTerran', 'broodling', 'hatchery', 'lair', 'hive', 'creepColony',
      'sunkenColony', 'sporeColony', 'spawningPool', 'evolutionChamber', 'hydraliskDen', 'extractor', 'spire',
      'greaterSpire', 'queensNest', 'nydusCanal', 'ultraliskCavern', 'defilerMound',
    ],
  },
  { race: 'Neutral', keys: ['mineral', 'geyser'] },
];

/** Wrap inner markup into a standalone, sized SVG document for rasterization. */
export const svgDoc = (inner: string): string =>
  `<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64">${inner}</svg>`;
